CREATE TABLE IF NOT EXISTS rating (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar
);
CREATE TABLE IF NOT EXISTS status (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar
);
CREATE TABLE IF NOT EXISTS genre (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS films (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
	description varchar(200),
	releaseDate timestamp,
	duration integer, 
	rating_id INTEGER REFERENCES rating (id)
	);
	
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  email varchar,
  login varchar NOT NULL,
  birthday timestamp
  );
  
CREATE TABLE IF NOT EXISTS friends (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users (id),
  friend_user_id INTEGER REFERENCES users (id),
  status_id INTEGER REFERENCES status (id)
);



CREATE TABLE IF NOT EXISTS likes (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  film_id INTEGER REFERENCES films (id),
  like_user_id INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS filmGenre (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  film_id INTEGER REFERENCES films (id),
  genre_id INTEGER REFERENCES genre (id)
);





  