CREATE TABLE IF NOT EXISTS films (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
	description varchar(200),
	releaseDate timestamp,
	duration integer, 
	rating_id integer
	);
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  email varchar,
  login varchar NOT NULL,
  birthday timestamp
  );
  